### ISSUE TITLE
Ollama: BadRequestError: 400 json: cannot unmarshal array into Go struct field Message.messages.content of type string

### ISSUE THREAD

**Issue by edarchis** [cdaein/rename-screenshot#1]
I am running the script on my macbook pro and need to run the model locally for security reasons. My config includes:
```
 "ollama": {
    "baseURL": "http://127.0.0.1:11434/v1/",
    "model": "llava:7b",
    "maxTokens": 30
  }
```
I had to use 127.0.0.1 because by default, ollama only listens to IPv4 and localhost is resolving to ::1. This cause "connection refused" errors. But now I'm getting:
```
BadRequestError: 400 json: cannot unmarshal array into Go struct field Message.messages.content of type string
    at APIError.generate (file:///Users/darcher/Dev/rename-screenshot/node_modules/openai/error.mjs:41:20)
    at OpenAI.makeStatusError (file:///Users/darcher/Dev/rename-screenshot/node_modules/openai/core.mjs:268:25)
    at OpenAI.makeRequest (file:///Users/darcher/Dev/rename-screenshot/node_modules/openai/core.mjs:311:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getNewName (file:///Users/darcher/Dev/rename-screenshot/dist/index.js:220:22)
    at async processFile (file:///Users/darcher/Dev/rename-screenshot/dist/index.js:194:36) {
  status: 400,
  headers: {
    'content-length': '169',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 25 Jul 2024 11:24:56 GMT'
  },
  request_id: undefined,
  error: {
    message: 'json: cannot unmarshal array into Go struct field Message.messages.content of type string',
    type: 'invalid_request_error',
    param: null,
    code: null
  },
  code: null,
  param: null,
  type: 'invalid_request_error'
}
```

ChatGPT suggested that it was because content was passed as an array rather than a string and suggested to add a JSON.Stringify on it:
```
      messages: [
        {
          role: "user",
          content: JSON.stringify([
            { type: "text", text: prompt },
            {
              type: "image_url",
              image_url: {
                // Either a URL of the image or the base64 encoded image data.
                url: base64string,
                // https://platform.openai.com/docs/guides/vision/low-or-high-fidelity-image-understanding
                // low detail is good enough to generate filename and more cost-effective
                detail: opts.detail,
              },
            },
          ]),
        },
      ],
```

However, this only results in a `SyntaxError: Unexpected end of JSON input`.

**Comment by cdaein** [comment]
Hi.
A few things you might check first are:
- when you visit `http://127.0.0.1:11434`, do you see `Ollama is running` message?
- are you using Ollama `0.2.8` (the latest version) ? Try `ollama --version` in the Terminal.

**Comment by cdaein** [comment]
You may also try this to see if it can handle `messages.content` as array:

```
curl http://127.0.0.1:11434/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "llava:7b",
        "messages": [
            {
                "role": "user",
                "content": [{ "type": "text", "text": "hello!" }]
            }
        ]
    }'
```

**Comment by edarchis** [comment]
Thanks for the steps, I am indeed running ollama 0.1.34. I installed it with brew install ollama.

I removed it and installed it from the main website. Most of the files are now working, only a portion of them get `Model stopped generating: length` which is probably due to file size. I can deal with that.

Thanks

**Comment by cdaein** [comment]
Great to hear!

The `length` warning is because the response exceeds the max token length. You can increase it in the `user.config.json` but then, the filename will get longer. I noticed that LLaVA tends to generate longer filenames than ChatGPT. You can also customize the prompt in the `index.ts` to ask for shorter names.
